version: 0.2

phases:
  install:
    commands:
      - echo "Download allurectl..."
      - wget https://github.com/allure-framework/allurectl/releases/latest/download/allurectl_linux_amd64 -O ./allurectl
      - chmod +x ./allurectl
  build:
    commands:
      - mvn package
      - |
        if [[ $CODEBUILD_BUILD_ID == "cusbo-ci-pipeline-stuff-build-api:*" ]]; then
              export ALLURE_UPLOAD="true"
        fi
  post_build:
    commands:
      - |
        if [[ $ALLURE_UPLOAD == "true" ]]; then
          echo "Uploading test reports to Allure TestOps"
          ./allurectl upload --launch-name "$CODEBUILD_RESOLVED_SOURCE_VERSION" ./target/allure-results
        fi
artifacts:
  files:
    - target/*.jar
