version: 0.2

phases:
  install:
    commands:
      - echo "Download allurectl..."
      - wget https://github.com/allure-framework/allurectl/releases/latest/download/allurectl_linux_amd64 -O ./allurectl
      - chmod +x ./allurectl
  build:
    commands:
      - mvn package -DskipTests
  post_build:
    commands:
      - bash ./upload_test_results.sh
artifacts:
  files:
    - target/*.jar
